globals:
  seed: 1213
  device: cuda
  num_epochs: 50
  main_metric: epoch_lwlrap
  minimize_metric: False
  input_key: image
  input_target_key: targets
  weights:
  folds:
    - 0
    - 1
    - 2
    - 3
    - 4

data:
  train_tp_path: input/train_tp.csv
  train_fp_path: input/train_fp.csv
  train_audio_path: input/train_32k
  test_audio_path: input/test_32k
  sample_submission_path: input/sample_submission.csv

dataset:
  train:
    name: LogmelMixupWithFPDataset
    params:
      sampling_rate: 32000
      duration: 5
      melspectrogram_parameters:
        n_mels: 128
        fmin: 20
        fmax: 16000
      pcen_parameters:
        gain: 0.98
        bias: 2
        power: 0.5
        time_constant: 0.4
        eps: 0.000001
      mixup_prob: 0.5
  valid:
    name: FasterMLSpectrogramDataset
    params:
      sampling_rate: 32000
      duration: 5
      melspectrogram_parameters:
        n_mels: 128
        fmin: 20
        fmax: 16000
      pcen_parameters:
        gain: 0.98
        bias: 2
        power: 0.5
        time_constant: 0.4
        eps: 0.000001
      centering: True
  test:
    name: FasterSpectrogramTestDataset
    params:
      sampling_rate: 32000
      duration: 5
      melspectrogram_parameters:
        n_mels: 128
        fmin: 20
        fmax: 16000
      pcen_parameters:
        gain: 0.98
        bias: 2
        power: 0.5
        time_constant: 0.4
        eps: 0.000001

transforms:
  train:
    - name: PinkNoiseSNR
      params:
        min_snr: 10.0
    - name: VolumeControl
      params:
        db_limit: 5
        mode: sine
  valid:
  test:

loss:
  name: Focal2WayStrongLoss
  params:
    weights:
      - 1.0
      - 0.5

optimizer:
  name: Adam
  params:
    lr: 0.001

scheduler:
  name: CosineAnnealingLR
  params:
    T_max: 10

split:
  name: KFold
  params:
    n_splits: 5
    random_state: 42
    shuffle: True

model:
  name: ResNestSED
  params:
    base_model_name: resnest50_fast_1s1x64d
    pretrained: True
    num_classes: 24
    interpolate_ratio: 30

loader:
  train:
    batch_size: 64
    shuffle: True
    num_workers: 10
  valid:
    batch_size: 64
    shuffle: False
    num_workers: 10
  test:
    batch_size: 64
    shuffle: False
    num_workers: 10

callbacks:
  - name: LWLRAPCallback
    params:
      input_key: targets
      output_key: logits
      prefix: lwlrap

inference:
  prediction_type: weak
