globals:
  seed: 1213
  device: cuda
  num_epochs: 55
  main_metric: epoch_lwlrap
  minimize_metric: False
  input_key: image
  input_target_key: targets
  weights:
  folds:
    - 0
    - 1
    - 2
    - 3
    - 4

data:
  train_tp_path: input/train_tp.csv
  train_fp_path: input/train_fp.csv
  train_audio_path: input/train_32k
  test_audio_path: input/test_32k
  sample_submission_path: input/sample_submission.csv

dataset:
  train:
    name: FasterMLSpectrogramDataset
    params:
      sampling_rate: 32000
      duration: 10
      melspectrogram_parameters:
        n_mels: 200
        n_fft: 2048
        fmin: 300
        fmax: 16000
      pcen_parameters:
        gain: 0.98
        bias: 2
        power: 0.5
        time_constant: 0.4
        eps: 0.000001
      img_size: [2048, 512]
  valid:
    name: FasterMLSpectrogramDataset
    params:
      sampling_rate: 32000
      duration: 10
      melspectrogram_parameters:
        n_mels: 200
        n_fft: 2048
        fmin: 300
        fmax: 16000
      pcen_parameters:
        gain: 0.98
        bias: 2
        power: 0.5
        time_constant: 0.4
        eps: 0.000001
      centering: True
      img_size: [2048, 512]
  test:
    name: FasterSpectrogramTestDataset
    params:
      sampling_rate: 32000
      duration: 10
      melspectrogram_parameters:
        n_mels: 200
        n_fft: 2048
        fmin: 300
        fmax: 16000
      pcen_parameters:
        gain: 0.98
        bias: 2
        power: 0.5
        time_constant: 0.4
        eps: 0.000001
      img_size: [2048, 512]

transforms:
  train:
    - name: PinkNoiseSNR
      params:
        min_snr: 10.0
    - name: PitchShift
      params:
        max_steps: 3
        sr: 32000
    - name: LibrosaNormalize
  valid:
    - name: LibrosaNormalize
  test:
    - name: LibrosaNormalize

loss:
  name: LogitBCEFocalLoss
  params:

optimizer:
  name: SAM
  base_optimizer: Adam
  params:
    lr: 0.001

scheduler:
  name: CosineAnnealingLR
  params:
    T_max: 10

split:
  name: KFold
  params:
    n_splits: 5
    random_state: 42
    shuffle: True

model:
  name: TimmEfficientNetSEDMax
  params:
    base_model_name: tf_efficientnet_b0_ns
    pretrained: True
    num_classes: 24

loader:
  train:
    batch_size: 16
    shuffle: True
    num_workers: 20
  valid:
    batch_size: 32
    shuffle: False
    num_workers: 20
  test:
    batch_size: 32
    shuffle: False
    num_workers: 20

runner: SAMRunner

callbacks:
  - name: LWLRAPCallback
    params:
      input_key: targets
      output_key: logits
      prefix: lwlrap
  - name: SchedulerCallback
    params:

inference:
  prediction_type: weak
