results:
  - submission: out/015_ResNest_strong_focal_5fold/submission/weak.csv
    oof: out/015_ResNest_strong_focal_5fold/submission/oof_weak.csv
    name: 015_focal
  - submission: out/009_ResNestSED_5fold/submission/weak.csv
    oof: out/009_ResNestSED_5fold/submission/oof_weak.csv
    name: 009_weak

data:
  data:
  train_tp_path: input/train_tp.csv
  train_fp_path: input/train_fp.csv
  train_audio_path: input/train
  test_audio_path: input/test
  sample_submission_path: input/sample_submission.csv

strategy:
  name: simple
  weights:
    - 0.7
    - 0.3
